# Generated by Django 4.1 on 2022-08-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='somewhere', max_length=100),
            preserve_default=False,
        ),
    ]
