# Generated by Django 4.1 on 2022-08-22 13:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_userfollow'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfollow',
            unique_together={('follower', 'followed')},
        ),
    ]
